from pathlib import Path
p = Path("client/src/pages/Home.tsx")
t = p.read_text()
t = t.replace('onCreate: (name: string, preset: string) => void', 'onCreate: (name: string, preset: string, brief: string, sourceUrl: string) => void')
t = t.replace('  const [brief, setBrief] = useState("");\n  const submit = () => { if (!name.trim()) { toast.error("Give your project a name first"); return; } onCreate(name.trim(), preset); };', '  const [brief, setBrief] = useState("");\n  const [sourceUrl, setSourceUrl] = useState("");\n  const submit = () => { if (!name.trim()) { toast.error("Dê um nome ao projeto primeiro"); return; } onCreate(name.trim(), preset, brief, sourceUrl); };')
t = t.replace('placeholder="Cole um briefing, roteiro, URL ou algumas ideias iniciais…"', 'placeholder="Cole um briefing, roteiro ou algumas ideias iniciais…"')
t = t.replace('</label></div><div className="mt-7 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="ghost" onClick={onClose}>Cancel</Button>', '</label><label className="grid gap-2"><span className="flex items-center justify-between text-xs font-bold">Importar página pública <span className="font-normal text-muted">Opcional</span></span><Input value={sourceUrl} onChange={(e) => setSourceUrl(e.target.value)} placeholder="https://exemplo.com/artigo" /></label></div><div className="mt-7 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="ghost" onClick={onClose}>Cancelar</Button>')
t = t.replace('  const create = (name: string, preset: string) => { createMutation.mutate({ name, preset }, { onSuccess: ({ project }) => { setModal(false); toast.success("Projeto criado"); if (project) navigate(`/editor/${project.id}`); }, onError: () => { const project = makeProject(name, preset); setProjects((current) => [project, ...current]); setModal(false); toast.info("Projeto salvo localmente enquanto o banco é conectado"); navigate(`/editor/${project.id}`); } }); };', '  const create = (name: string, preset: string, brief: string, sourceUrl: string) => { createMutation.mutate({ name, preset, brief: sourceUrl ? undefined : brief }, { onSuccess: ({ project }) => { setModal(false); if (!project) return; if (sourceUrl) importMutation.mutate({ projectId: project.id, url: sourceUrl }, { onSuccess: () => toast.success("Página importada e cenas geradas"), onError: (error) => toast.error(error.message) }); else toast.success("Projeto criado"); navigate(`/editor/${project.id}`); }, onError: () => { const project = makeProject(name, preset); setProjects((current) => [project, ...current]); setModal(false); toast.info("Projeto salvo localmente enquanto o banco é conectado"); navigate(`/editor/${project.id}`); } }); };')
t = t.replace('  const createMutation = trpc.projects.create.useMutation();\n  const renderMutation', '  const createMutation = trpc.projects.create.useMutation();\n  const importMutation = trpc.projects.importSource.useMutation();\n  const renderMutation')
old = '  const render = (id: string) => { setProjects((current) => current.map((project) => project.id === id ? { ...project, status: "rendering", updated: "Just now" } : project)); toast.success("Render adicionado à fila", { description: "O processamento está compondo as cenas." }); setTimeout(() => setProjects((current) => current.map((project) => project.id === id ? { ...project, status: "ready", updated: "Just now" } : project)), 4200); };'
new = '  const render = (id: string) => { if (/^\\d+$/.test(id)) { renderMutation.mutate({ projectId: Number(id), engine: "ffmpeg" }, { onSuccess: (job) => { toast.success("Render pronto", { description: "MP4, SRT e VTT foram salvos no armazenamento." }); if (job?.mp4Url) window.open(job.mp4Url, "_blank", "noopener,noreferrer"); }, onError: (error) => toast.error(error.message) }); return; } setProjects((current) => current.map((project) => project.id === id ? { ...project, status: "rendering", updated: "Agora" } : project)); toast.success("Render adicionado à fila"); };'
t = t.replace(old, new)
p.write_text(t)

r = Path("client/src/lib/reel-data.ts")
t = r.read_text()
t = t.replace('return { draft: "Draft", rendering: "Rendering", ready: "Ready" }[status];', 'return { draft: "Rascunho", rendering: "Renderizando", ready: "Pronto" }[status];')
t = t.replace('return {\n    draft: "bg-ink/6 text-muted",\n    rendering: "bg-amber/12 text-amber",\n    ready: "bg-mint/14 text-emerald-700",\n  }[status];', 'return {\n    draft: "bg-ink/6 text-muted",\n    rendering: "bg-amber/12 text-amber",\n    ready: "bg-mint/14 text-emerald-700",\n  }[status];')
r.write_text(t)
