from pathlib import Path

replacements = {
    "Reel Studio": "Reel Studio",
    "Northstar Studio": "Northstar Studio",
    "Creator guide": "Guia do criador",
    "Keyboard shortcuts": "Atalhos de teclado",
    "Search your studio": "Buscar no estúdio",
    "New project": "Novo projeto",
    "Good morning": "Bom dia",
    "Good afternoon": "Boa tarde",
    "Good evening": "Boa noite",
    "LOCAL-FIRST CONTENT STUDIO": "ESTÚDIO DE CONTEÚDO LOCAL-FIRST",
    "Local-first · AI optional": "Local-first · IA opcional",
    "Make your next reel feel inevitable.": "Faça seu próximo reel parecer inevitável.",
    "Turn a brief, script, screenshot, recording, or podcast into finished content — with a calmer production flow.": "Transforme um briefing, roteiro, captura, gravação ou podcast em conteúdo pronto — com um fluxo de produção mais tranquilo.",
    "Create a project": "Criar um projeto",
    "Explore templates": "Explorar templates",
    "36 renders this month": "36 renders este mês",
    "Private by default": "Privado por padrão",
    "No key required": "Sem chave necessária",
    "Projects this month": "Projetos este mês",
    "Minutes rendered": "Minutos renderizados",
    "Avg. completion": "Conclusão média",
    "Your projects": "Seus projetos",
    "Keep the ideas moving.": "Mantenha as ideias em movimento.",
    "All projects": "Todos os projetos",
    "Start another project": "Começar outro projeto",
    "From a brief, script, or recording": "A partir de briefing, roteiro ou gravação",
    "No projects match that search.": "Nenhum projeto corresponde à busca.",
    "Try a different search or create something new.": "Tente outra busca ou crie algo novo.",
    "View all projects →": "Ver todos os projetos →",
    "Production queue": "Fila de produção",
    "items in render queue": "itens na fila de renderização",
    "Open queue": "Abrir fila",
    "Recent activity": "Atividade recente",
    "A little momentum": "Um pouco de ritmo",
    "A calmer production loop": "Um ciclo de produção mais tranquilo",
    "Write, design, produce — then reuse your best scenes across every format.": "Escreva, desenhe, produza — e reutilize suas melhores cenas em qualquer formato.",
    "Show me a tip →": "Mostrar uma dica →",
    "Made for motion": "Feito para movimento",
    "Works wherever your audience is.": "Funciona onde sua audiência estiver.",
    "Native presets": "Presets nativos",
    "New project": "Novo projeto",
    "Start with a spark.": "Comece com uma faísca.",
    "Choose a production shape now. You can fine-tune every scene later in the editor.": "Escolha uma estrutura de produção. Você pode ajustar cada cena depois no editor.",
    "Project name": "Nome do projeto",
    "Choose a starting point": "Escolha um ponto de partida",
    "Brief or rough idea": "Briefing ou ideia inicial",
    "Paste a brief, script, URL, or a few rough ideas…": "Cole um briefing, roteiro, URL ou algumas ideias iniciais…",
    "Create project": "Criar projeto",
    "Production library": "Biblioteca de produção",
    "Templates that know the beat.": "Templates que entendem o ritmo.",
    "Start with a production shape, then make it yours.": "Comece com uma estrutura de produção e deixe-a com a sua cara.",
    "Save a favorite": "Salvar favorito",
    "Search templates": "Buscar templates",
    "All formats": "Todos os formatos",
    "Use template": "Usar template",
    "6 scene structure": "Estrutura de 6 cenas",
    "Starter gallery": "Galeria inicial",
    "A shape for every story.": "Uma estrutura para cada história.",
    "Sample projects you can use as a starting point.": "Projetos de exemplo para você começar.",
    "View all": "Ver todos",
    "Use this shape →": "Usar esta estrutura →",
    "Voice library": "Biblioteca de vozes",
    "Give the idea a voice.": "Dê voz à sua ideia.",
    "Preview voices, set a default, and keep your tone consistent.": "Ouça as vozes, escolha uma padrão e mantenha seu tom consistente.",
    "Clone a voice": "Clonar uma voz",
    "Search voices": "Buscar vozes",
    "All languages": "Todos os idiomas",
    "Default voice": "Voz padrão",
    "Use voice": "Usar voz",
    "Voice preview": "Prévia da voz",
    "Your idea deserves room to land.": "Sua ideia merece espaço para chegar.",
    "Natural pacing · studio tone": "Ritmo natural · tom de estúdio",
    "Preview voice": "Ouvir prévia",
    "Local voices are available without an API key. Cloud providers can be connected in Settings.": "Vozes locais estão disponíveis sem chave de API. Provedores em nuvem podem ser conectados em Configurações.",
    "Workspace settings": "Configurações do espaço",
    "Make the studio yours.": "Deixe o estúdio com a sua cara.",
    "Tune the defaults that shape every new production.": "Ajuste os padrões que orientam cada nova produção.",
    "Changes are stored in this local workspace.": "As alterações ficam salvas neste espaço local.",
    "Workspace name": "Nome do espaço",
    "A label for your private production space.": "Um nome para seu espaço privado de produção.",
    "Default language": "Idioma padrão",
    "Used for captions, voice previews, and suggested copy.": "Usado para legendas, prévias de voz e textos sugeridos.",
    "Autosave drafts": "Salvar rascunhos automaticamente",
    "Keep edits safe while you move through the story.": "Mantenha as edições seguras enquanto avança na história.",
    "Default format": "Formato padrão",
    "The canvas used when you start a new project.": "A tela usada ao iniciar um novo projeto.",
    "Render engine": "Motor de renderização",
    "Choose the engine that powers your final render.": "Escolha o motor que gera seu render final.",
    "Output privacy": "Privacidade da saída",
    "Renders stay local until you explicitly download or share them.": "Os renders permanecem locais até você baixar ou compartilhar.",
    "Private by default": "Privado por padrão",
    "Generate captions": "Gerar legendas",
    "Create a caption track whenever you produce.": "Criar uma faixa de legendas em toda produção.",
    "Caption style": "Estilo de legenda",
    "The style applied to new caption tracks.": "O estilo aplicado às novas faixas de legenda.",
    "Safe area": "Área segura",
    "Keep words inside the comfortable mobile reading zone.": "Mantenha as palavras dentro da área confortável de leitura no celular.",
    "Settings are local to this workspace.": "As configurações são locais deste espaço.",
    "Save changes": "Salvar alterações",
    "Need a hand?": "Precisa de ajuda?",
    "Read the creator guide or send a note to": "Leia o guia do criador ou escreva para",
    "Contact support →": "Falar com suporte →",
    "Danger zone": "Zona de perigo",
    "Restore the starter project data for this demo workspace.": "Restaure os dados iniciais deste espaço de demonstração.",
    "Reset demo data": "Restaurar dados de demonstração",
    "Draft synced": "Rascunho sincronizado",
    "All changes saved": "Todas as alterações salvas",
    "Scene line": "Texto da cena",
    "Media treatment": "Tratamento de mídia",
    "Caption style": "Estilo da legenda",
    "Regenerate scene": "Regenerar cena",
    "Add scene": "Adicionar cena",
    "New scene": "Nova cena",
    "Add your next beat.": "Adicione o próximo momento.",
    "Scene added": "Cena adicionada",
    "Scene removed": "Cena removida",
    "Render & export": "Renderizar e exportar",
    "Create verified media, captions, and transcript files from this revision.": "Crie mídia, legendas e transcrições verificadas a partir desta versão.",
    "Estimated render": "Render estimado",
    "Your output stays private until you download or share it.": "Sua saída permanece privada até você baixar ou compartilhar.",
    "Start render": "Iniciar render",
    "Live preview": "Prévia ao vivo",
    "Music volume": "Volume da música",
    "Caption editor opened": "Editor de legendas aberto",
    "Version history is coming soon": "O histórico de versões estará disponível em breve",
    "Changes restored": "Alterações restauradas",
    "Project saved": "Projeto salvo",
    "Render queued": "Render adicionado à fila",
    "Your production worker is composing the scenes.": "O processamento está compondo as cenas.",
    "Render ready": "Render pronto",
    "Your MP4 and caption files are ready.": "Seu MP4 e arquivos de legenda estão prontos.",
    "Project actions are coming soon": "As ações do projeto estarão disponíveis em breve",
}

roots = [Path("client/src")]
for root in roots:
    for path in list(root.rglob("*.tsx")) + [Path("client/src/lib/reel-data.ts")]:
        text = path.read_text()
        updated = text
        for source, target in replacements.items():
            updated = updated.replace(source, target)
        if updated != text:
            path.write_text(updated)
