from pathlib import Path
p=Path("client/src/lib/reel-data.ts")
t=p.read_text()
repls={
'"Share project"':'"Compartilhar projeto"',
'"Export settings"':'"Configurações de exportação"',
'"Save draft"':'"Salvar rascunho"',
'"Saved just now"':'"Salvo agora"',
'"Workspace"':'"Espaço de trabalho"',
'"Integrations"':'"Integrações"',
'"Settings saved"':'"Configurações salvas"',
'"Locked scenes stay fixed during regeneration."':'"Cenas bloqueadas permanecem fixas durante a regeneração."',
'"Search soundtracks…"':'"Buscar trilhas…"',
'"Download after render"':'"Baixar após o render"',
'"Include captions"':'"Incluir legendas"',
'"Open last project"':'"Abrir último projeto"',
'"View templates"':'"Ver templates"',
'"Open settings"':'"Abrir configurações"',
'["Projects", "Templates", "Voices"]':'["Projetos", "Templates", "Vozes"]',
'"Product launch / Aurora"':'"Lançamento de produto / Aurora"',
'"Founder story — from zero"':'"História da fundadora — do zero"',
'"Why teams ship faster"':'"Por que equipes entregam mais rápido"',
'"Product Launch"':'"Lançamento de produto"',
'"Creator Punch"':'"Impacto do criador"',
'"Editorial Explainer"':'"Explicador editorial"',
'"Data Story"':'"História com dados"',
'"Developer Demo"':'"Demo para desenvolvedores"',
'"Cinematic Brand"':'"Marca cinematográfica"',
'"Hook"':'"Gancho"',
'"Context"':'"Contexto"',
'"Proof"':'"Prova"',
'"Feature"':'"Recurso"',
'"CTA"':'"CTA"',
'"The old way is over."':'"O jeito antigo acabou."',
'"Ideas move at the speed of your workflow."':'"Ideias avançam na velocidade do seu fluxo."',
'"One brief. Every format."':'"Um briefing. Todos os formatos."',
'"Create, refine, publish."':'"Crie, refine, publique."',
'"Bold reveal · 9:16"':'"Revelação marcante · 9:16"',
'"Fast cuts · 9:16"':'"Cortes rápidos · 9:16"',
'"Clean story · 16:9"':'"História limpa · 16:9"',
'"Charts & numbers · 1:1"':'"Gráficos e números · 1:1"',
'"Product walkthrough · 16:9"':'"Demonstração do produto · 16:9"',
'"Atmospheric · 9:16"':'"Atmosférico · 9:16"',
'"Warm · confident"':'"Acolhedora · confiante"',
'"Clear · energetic"':'"Clara · energética"',
'"Natural · bright"':'"Natural · luminosa"',
'"Soft · cinematic"':'"Suave · cinematográfica"',
'"English (US)"':'"Inglês (EUA)"',
'"English (UK)"':'"Inglês (Reino Unido)"',
'"Español (ES)"':'"Espanhol (Espanha)"',
'"Ambient Glow"':'"Brilho ambiente"',
'"Lo-fi Chill"':'"Lo-fi tranquilo"',
'"Upbeat Drive"':'"Ritmo acelerado"',
'"Cinematic Tension"':'"Tensão cinematográfica"',
'"Developer"':'"Desenvolvedor"',
'"Instagram Reels"':'"Reels do Instagram"',
'"YouTube Shorts"':'"Shorts do YouTube"',
'"LinkedIn"':'"LinkedIn"',
}
for a,b in repls.items(): t=t.replace(a,b)
p.write_text(t)
