from pathlib import Path

home = Path("client/src/pages/Home.tsx")
text = home.read_text()
text = text.replace('import { presets, starterProjects, sampleStats, recentActivity, statusLabel, statusTone, colorClasses, makeProject, safeParse, storageKeys, timeGreeting, ownerName, heroEyebrow, heroTitle, heroSubhead, formatOptions, engineOptions, defaultSettings, Project, defaultFormat, defaultVoice, defaultSoundtrack, defaultCaptionStyle, soundtracks, voices, quickTips, platformLabels, renderQueueStatus } from "@/lib/reel-data";', 'import { presets, starterProjects, sampleStats, recentActivity, statusLabel, statusTone, colorClasses, makeProject, safeParse, storageKeys, timeGreeting, ownerName, heroEyebrow, heroTitle, heroSubhead, formatOptions, engineOptions, defaultSettings, Project, defaultFormat, defaultVoice, defaultSoundtrack, defaultCaptionStyle, soundtracks, voices, quickTips, platformLabels, renderQueueStatus } from "@/lib/reel-data";\nimport { trpc } from "@/lib/trpc";')
old = '  const [projects, setProjects] = useState<Project[]>(() => safeParse(localStorage.getItem(storageKeys.projects), starterProjects));\n  const [query, setQuery] = useState("");'
new = '  const projectsQuery = trpc.projects.list.useQuery(undefined, { retry: false });\n  const createMutation = trpc.projects.create.useMutation();\n  const renderMutation = trpc.renders.start.useMutation();\n  const [projects, setProjects] = useState<Project[]>(() => safeParse(localStorage.getItem(storageKeys.projects), starterProjects));\n  const [query, setQuery] = useState("");'
text = text.replace(old, new)
old = '  useEffect(() => localStorage.setItem(storageKeys.projects, JSON.stringify(projects)), [projects]);\n  const filtered'
new = '  useEffect(() => localStorage.setItem(storageKeys.projects, JSON.stringify(projects)), [projects]);\n  useEffect(() => {\n    if (!projectsQuery.data) return;\n    setProjects(projectsQuery.data.map((project) => ({ id: String(project.id), name: project.name, type: project.type, preset: project.preset, status: project.status === "failed" ? "draft" : project.status, scenes: 0, duration: "00:00", updated: new Date(project.updatedAt).toLocaleDateString("pt-BR"), color: project.preset.includes("Creator") ? "violet" : project.preset.includes("Data") ? "mint" : "coral" })));\n  }, [projectsQuery.data]);\n  const filtered'
text = text.replace(old, new)
old = '  const create = (name: string, preset: string) => { const project = makeProject(name, preset); setProjects((current) => [project, ...current]); setModal(false); toast.success("Projeto created"); navigate(`/editor/${project.id}`); };'
if old not in text:
    old = '  const create = (name: string, preset: string) => { const project = makeProject(name, preset); setProjects((current) => [project, ...current]); setModal(false); toast.success("Project created"); navigate(`/editor/${project.id}`); };'
new = '  const create = (name: string, preset: string) => { createMutation.mutate({ name, preset }, { onSuccess: ({ project }) => { setModal(false); toast.success("Projeto criado"); if (project) navigate(`/editor/${project.id}`); }, onError: () => { const project = makeProject(name, preset); setProjects((current) => [project, ...current]); setModal(false); toast.info("Projeto salvo localmente enquanto o banco é conectado"); navigate(`/editor/${project.id}`); } }); };'
text = text.replace(old, new)
old = '  const render = (id: string) => { setProjects((current) => current.map((project) => project.id === id ? { ...project, status: "rendering", updated: "Just now" } : project)); toast.success("Render queued", { description: "Your production worker is composing the scenes." }); setTimeout(() => setProjects((current) => current.map((project) => project.id === id ? { ...project, status: "ready", updated: "Just now" } : project)), 4200); };'
new = '  const render = (id: string) => { if (/^\\d+$/.test(id)) { renderMutation.mutate({ projectId: Number(id), engine: "ffmpeg" }, { onSuccess: (job) => { toast.success("Render pronto", { description: "MP4, SRT e VTT foram salvos no armazenamento." }); if (job?.mp4Url) window.open(job.mp4Url, "_blank", "noopener,noreferrer"); }, onError: (error) => toast.error(error.message) }); return; } setProjects((current) => current.map((project) => project.id === id ? { ...project, status: "rendering", updated: "Agora" } : project)); toast.success("Render adicionado à fila"); };'
text = text.replace(old, new)
home.write_text(text)

editor = Path("client/src/pages/Editor.tsx")
text = editor.read_text()
text = text.replace('ArrowLeft, Check, ChevronDown, CircleHelp, Download, Film', 'ArrowLeft, Check, ChevronDown, CircleHelp, Download, Film, Upload')
text = text.replace('import { getProject, sceneSamples, soundtracks, voices, formatDuration, editorTabs, productionStages, defaultFormat, defaultCaptionStyle, defaultVoice, defaultSoundtrack, statusTone, colorClasses, Project, starterProjects, statusLabel, storageKeys, safeParse, renderFormats, captionStyles, transitionOptions, canvasDimensions } from "@/lib/reel-data";', 'import { getProject, sceneSamples, soundtracks, voices, formatDuration, editorTabs, productionStages, defaultFormat, defaultCaptionStyle, defaultVoice, defaultSoundtrack, statusTone, colorClasses, Project, starterProjects, statusLabel, storageKeys, safeParse, renderFormats, captionStyles, transitionOptions, canvasDimensions } from "@/lib/reel-data";\nimport { trpc } from "@/lib/trpc";')
old = '  const project = getProject(params?.id);\n  const [scenes, setScenes] = useState(sceneSamples);'
new = '  const project = getProject(params?.id);\n  const numericId = Number(params?.id);\n  const projectQuery = trpc.projects.get.useQuery({ id: numericId }, { enabled: Number.isInteger(numericId) && numericId > 0, retry: false });\n  const saveSceneMutation = trpc.projects.updateScene.useMutation();\n  const renderMutation = trpc.renders.start.useMutation();\n  const uploadMutation = trpc.projects.uploadAsset.useMutation();\n  const [scenes, setScenes] = useState(sceneSamples);'
text = text.replace(old, new)
old = '  useEffect(() => { if (!playing) return; const timer = setInterval(() => setActive((current) => (current + 1) % scenes.length), 3200); return () => clearInterval(timer); }, [playing, scenes.length]);'
new = '  useEffect(() => { if (!playing) return; const timer = setInterval(() => setActive((current) => (current + 1) % scenes.length), 3200); return () => clearInterval(timer); }, [playing, scenes.length]);\n  useEffect(() => { if (!projectQuery.data) return; setProjectName(projectQuery.data.project.name); setScenes(projectQuery.data.scenes.map((scene, index) => ({ id: scene.id, label: scene.label, title: scene.title, caption: scene.caption, duration: formatDuration(scene.durationMs / 1000), accent: ["coral", "violet", "mint", "sky", "amber"][index % 5] as "coral" | "violet" | "mint" | "sky" | "amber" }))); }, [projectQuery.data]);'
text = text.replace(old, new)
old = '  const save = () => { const projects = safeParse<Project[]>(localStorage.getItem(storageKeys.projects), starterProjects); localStorage.setItem(storageKeys.projects, JSON.stringify(projects.map((item) => item.id === project.id ? { ...item, name: projectName, scenes: scenes.length, updated: "Just now" } : item))); toast.success("Projeto saved"); };'
if old not in text:
    old = '  const save = () => { const projects = safeParse<Project[]>(localStorage.getItem(storageKeys.projects), starterProjects); localStorage.setItem(storageKeys.projects, JSON.stringify(projects.map((item) => item.id === project.id ? { ...item, name: projectName, scenes: scenes.length, updated: "Just now" } : item))); toast.success("Project saved"); };'
new = '  const save = () => { const scene = scenes[active]; if (Number.isInteger(numericId) && numericId > 0 && typeof scene?.id === "number") { saveSceneMutation.mutate({ projectId: numericId, sceneId: scene.id, title: scene.title, caption: scene.caption, durationMs: Math.max(1000, Math.round(parseFloat(scene.duration.replace(":", ".")) * 1000)) }, { onSuccess: () => toast.success("Projeto salvo"), onError: (error) => toast.error(error.message) }); return; } const projects = safeParse<Project[]>(localStorage.getItem(storageKeys.projects), starterProjects); localStorage.setItem(storageKeys.projects, JSON.stringify(projects.map((item) => item.id === project.id ? { ...item, name: projectName, scenes: scenes.length, updated: "Agora" } : item))); toast.success("Projeto salvo"); };'
text = text.replace(old, new)
old = '  const render = () => { setShowRender(false); setProgress(10); toast.success("Render adicionado à fila", { description: "O processamento está compondo as cenas." }); const timer = setInterval(() => setProgress((value) => { if (value >= 100) { clearInterval(timer); toast.success("Render pronto", { description: "Seu MP4 e arquivos de legenda estão prontos." }); return 100; } return value + 15; }), 600); };'
new = '  const render = () => { if (Number.isInteger(numericId) && numericId > 0) { setShowRender(false); setProgress(10); renderMutation.mutate({ projectId: numericId, engine: "ffmpeg" }, { onSuccess: (job) => { setProgress(100); toast.success("Render pronto", { description: "MP4, SRT e VTT foram salvos no armazenamento." }); if (job?.mp4Url) window.open(job.mp4Url, "_blank", "noopener,noreferrer"); }, onError: (error) => { setProgress(0); toast.error(error.message); } }); return; } setShowRender(false); setProgress(10); toast.success("Render adicionado à fila"); };\n  const uploadMedia = (file: File) => { if (!(Number.isInteger(numericId) && numericId > 0)) { toast.info("Salve o projeto no banco antes de enviar mídia"); return; } const reader = new FileReader(); reader.onload = () => { uploadMutation.mutate({ projectId: numericId, fileName: file.name, mimeType: file.type || "application/octet-stream", dataUrl: String(reader.result) }, { onSuccess: () => toast.success("Mídia enviada para o armazenamento"), onError: (error) => toast.error(error.message) }); }; reader.readAsDataURL(file); };'
text = text.replace(old, new)
text = text.replace('<Button variant="outline" onClick={save} className="bg-white"><Save className="size-4" />Salvar</Button>', '<label className="flex cursor-pointer items-center gap-2 rounded-xl border border-ink/8 bg-white px-3 py-2 text-xs font-bold"><Upload className="size-4" />Mídia<input type="file" accept="image/*,video/*,audio/*" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) uploadMedia(file); }} /></label><Button variant="outline" onClick={save} className="bg-white"><Save className="size-4" />Salvar</Button>')
editor.write_text(text)
