from pathlib import Path
p=Path("client/src/pages/Editor.tsx")
t=p.read_text()
t=t.replace('  const uploadMutation = trpc.projects.uploadAsset.useMutation();\n', '  const uploadMutation = trpc.projects.uploadAsset.useMutation();\n  const cartesiaVoicesQuery = trpc.projects.listVoices.useQuery(undefined, { retry: false });\n  const generateVoiceMutation = trpc.projects.generateVoice.useMutation();\n')
t=t.replace('  const [progress, setProgress] = useState(24);\n', '  const [progress, setProgress] = useState(24);\n  useEffect(() => { if (cartesiaVoicesQuery.data?.length && !cartesiaVoicesQuery.data.some((item) => item.name === voice)) setVoice(cartesiaVoicesQuery.data[0].name); }, [cartesiaVoicesQuery.data, voice]);\n')
old='setScenes(projectQuery.data.scenes.map((scene, index) => ({ id: scene.id, label: scene.label, title: scene.title, caption: scene.caption, duration: formatDuration(scene.durationMs / 1000), accent: ["coral", "violet", "mint", "sky", "amber"][index % 5] as "coral" | "violet" | "mint" | "sky" | "amber" })));'
new='setScenes(projectQuery.data.scenes.map((scene, index) => ({ id: scene.id, label: scene.label, title: scene.title, caption: scene.caption, duration: formatDuration(scene.durationMs / 1000), accent: ["coral", "violet", "mint", "sky", "amber"][index % 5] as "coral" | "violet" | "mint" | "sky" | "amber", voiceId: scene.voiceId ?? undefined, voiceName: scene.voiceName ?? undefined, voiceLanguage: scene.voiceLanguage ?? undefined, voiceAudioUrl: scene.voiceAudioUrl ?? undefined, voiceStatus: scene.voiceStatus })));'
if old not in t: raise SystemExit('scene query mapping not found')
t=t.replace(old,new)
t=t.replace('  const uploadMedia = (file: File) => {', '  const generateVoice = () => { const current = activeScene as typeof activeScene & { id: number; voiceId?: string; voiceName?: string; voiceLanguage?: string; voiceAudioUrl?: string; voiceStatus?: string }; const selected = cartesiaVoicesQuery.data?.find((item) => item.name === voice); if (!(Number.isInteger(numericId) && numericId > 0) || !selected || !current) { toast.info("Abra um projeto salvo e selecione uma voz Cartesia"); return; } generateVoiceMutation.mutate({ projectId: numericId, sceneId: current.id, voiceId: selected.id, voiceName: selected.name, language: selected.language || "pt-BR", text: current.caption }, { onSuccess: (scene) => { setScenes(scenes.map((item, index) => index === active ? { ...item, voiceId: scene?.voiceId ?? selected.id, voiceName: scene?.voiceName ?? selected.name, voiceLanguage: scene?.voiceLanguage ?? selected.language, voiceAudioUrl: scene?.voiceAudioUrl ?? undefined, voiceStatus: scene?.voiceStatus } : item)); toast.success("Narração gerada com Cartesia"); }, onError: (error) => toast.error(error.message) }); };\n  const uploadMedia = (file: File) => {')
old_audio='}{tab === "Audio" && <div className="mt-5 space-y-4"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-muted">Audio mix</p><h3 className="mt-1 text-sm font-black">Give the story a pulse.</h3></div><label className="grid gap-2"><span className="text-[11px] font-bold text-muted">Voiceover</span><select value={voice} onChange={(e) => setVoice(e.target.value)} className="rounded-xl border border-ink/8 bg-white px-3 py-2.5 text-xs font-bold outline-none focus:border-coral">{voices.map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label className="grid gap-2"><span className="text-[11px] font-bold text-muted">Music</span><select value={music} onChange={(e) => setMusic(e.target.value)} className="rounded-xl border border-ink/8 bg-white px-3 py-2.5 text-xs font-bold outline-none focus:border-coral">{soundtracks.map((item) => <option key={item}>{item}</option>)}</select></label><div className="rounded-2xl border border-ink/8 bg-white p-3"><div className="flex items-center gap-2"><Volume2 className="size-4 text-coral" /><span className="text-xs font-bold">Volume da música</span><span className="ml-auto text-[10px] text-muted">24%</span></div><input type="range" className="mt-3 w-full accent-coral" defaultValue="24" /></div></div>}'
new_audio='}{tab === "Audio" && <div className="mt-5 space-y-4"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-muted">Narração e áudio</p><h3 className="mt-1 text-sm font-black">Dê voz à cena ativa.</h3></div><label className="grid gap-2"><span className="text-[11px] font-bold text-muted">Voz Cartesia</span><select value={voice} onChange={(e) => setVoice(e.target.value)} className="rounded-xl border border-ink/8 bg-white px-3 py-2.5 text-xs font-bold outline-none focus:border-coral">{(cartesiaVoicesQuery.data?.length ? cartesiaVoicesQuery.data : voices.map((item) => ({ id: item.name, name: item.name, language: item.language, description: item.role }))).map((item) => <option key={item.id} value={item.name}>{item.name} · {item.language}</option>)}</select></label><button disabled={generateVoiceMutation.isPending || !cartesiaVoicesQuery.data?.length} onClick={generateVoice} className="flex w-full items-center justify-center gap-2 rounded-xl bg-coral py-3 text-xs font-black text-white hover:bg-coral/90 disabled:cursor-not-allowed disabled:opacity-50"><Mic2 className="size-3.5" />{generateVoiceMutation.isPending ? "Gerando narração…" : "Gerar narração da cena"}</button><div className="rounded-2xl border border-ink/8 bg-ink/5 p-3"><div className="flex items-center gap-2"><Volume2 className="size-4 text-coral" /><span className="text-xs font-bold">Status da cena</span><span className="ml-auto text-[10px] font-black text-muted">{(activeScene as typeof activeScene & { voiceStatus?: string }).voiceStatus === "ready" ? "Áudio pronto" : "Ainda sem áudio"}</span></div>{(activeScene as typeof activeScene & { voiceAudioUrl?: string }).voiceAudioUrl && <audio controls src={(activeScene as typeof activeScene & { voiceAudioUrl?: string }).voiceAudioUrl} className="mt-3 w-full" />}</div><label className="grid gap-2"><span className="text-[11px] font-bold text-muted">Trilha musical</span><select value={music} onChange={(e) => setMusic(e.target.value)} className="rounded-xl border border-ink/8 bg-white px-3 py-2.5 text-xs font-bold outline-none focus:border-coral">{soundtracks.map((item) => <option key={item}>{item}</option>)}</select></label><div className="rounded-2xl border border-ink/8 bg-white p-3"><div className="flex items-center gap-2"><Volume2 className="size-4 text-coral" /><span className="text-xs font-bold">Volume da música</span><span className="ml-auto text-[10px] text-muted">24%</span></div><input type="range" className="mt-3 w-full accent-coral" defaultValue="24" /></div></div>}'
if old_audio not in t: raise SystemExit('audio section not found')
t=t.replace(old_audio,new_audio)
p.write_text(t)
